export const cardData = [
    {
        title: "Gatunki muzyczne",
        content: [
            "rock",
            "heavy metal",
            "muzyka klasyczna",
            "funk",
            "hip hop",
            "pop",
            "techno",
            "blues",
            "rap",
            "punk",
            "indie",
            "disco polo",
            "country",
            "house",
            "disco",
            "reggae",
        ],
    },

    {
        title: "Gatunki filmowe",
        content: [
            "horror",
            "komedia romantyczna",
            "kryminał",
            "musical",
            "akcja",
            "western",
            "niemy",
            "animacja",
            "thriller",
            "komedia",
            "wojenny",
            "dramat",
            "science fiction",
            "Bollywood",
            "dokumentalny",
            "katastroficzny",
        ],
    },

    {
        title: "Znane filmy",
        content: [
            "Park jurajski",
            "Transformers",
            "E.T",
            "Kiler",
            "Indiana Jones i Świątynia Zagłady",
            "Kevin sam w domu",
            "King Kong",
            "Rocky",
            "Szczęki",
            "Dzień świra",
            "Czarnoksiężnik z Oz",
            "Ojciec chrzestny",
            "The Avengers",
            "Titanic",
            "Matrix",
            "Avatar",
        ],
    },

    {
        title: "Pod wodą",
        content: [
            "rozgwiazda",
            "foka",
            "kałamarnica",
            "błazenek",
            "rekin",
            "delfin",
            "konik morski",
            "krewetka",
            "syrena",
            "ośmiornica",
            "homar",
            "krab",
            "żółw",
            "meduza",
            "orka",
            "płaszczka",
        ],
    },

    {
        title: "Mityczne stworzenia",
        content: [
            "Pegaz",
            "jednorożec",
            "syrena",
            "Hydra",
            "Meduza",
            "smok",
            "Feniks",
            "yeti",
            "cyklop",
            "wilkołak",
            "potwór z Loch Ness",
            "Minotaur",
            "Sfinks",
            "troll",
            "wampir",
            "Centaur",
        ],
    },

    {
        title: "Znane budowle",
        content: [
            "piramidy w Gizie",
            "wieża Eiffla",
            "Statua Wolności",
            "Big Ben",
            "Stonehenge",
            "katedra w Notre Dame",
            "Koloseum",
            "opera w Sydney",
            "statua Chrystusa w Rio de Janerio",
            "Machu Picchu",
            "Tadż Mahal",
            "Pałac Kultury i Nauki",
            "Wielki Mur Chiński",
            "Akropol",
            "bazylika w Licheniu",
            "Krzywa Wieża w Pizie",
        ],
    },

    {
        title: "Dyscypliny sportowe",
        content: [
            "piłka nożna",
            "boks",
            "golf",
            "snooker",
            "koszykówka",
            "rugby",
            "żeglarstwo",
            "skoki narciarskie",
            "tenis",
            "badminton",
            "żużel",
            "zapasy",
            "hokej",
            "siatkówka",
            "triatlon",
            "kolarstwo",
        ],
    },

    {
        title: "Tatuaże",
        content: ["gwiazdy", "anioł", "skrzydła", "smok", "orzeł", "delfin", "serce", "czaszka", "miecz", "tygrys", "jaskółka", "róża", "motyl", "krzyż", "jednorożec", "kotwica"],
    },

    {
        title: "Zabawki",
        content: [
            "klocki",
            "koń na biegunach",
            "pistolet na wodę",
            "bączek",
            "kostka Rubika",
            "piłka",
            "maskotka",
            "plastelina",
            "jo-jo",
            "frisbee",
            "samochodziki",
            "lalka",
            "skakanka",
            "puzzle",
            "hula-hop",
            "latawiec",
        ],
    },

    {
        title: "Bajki i baśnie",
        content: [
            "Kopciuszek",
            "Królowa Śniegu",
            "Brzydkie kaczątko",
            "Kot w butach",
            "Królewna Śnieżka",
            "Roszpunka",
            "Aladyn",
            "Księżniczka na ziarnku grochu",
            "Piotruś Pan",
            "Czerwony Kapturek",
            "Pinokio",
            "Piękna i Bestia",
            "Śpiąca królewna",
            "Jaś i Małgosia",
            "O rybaku i złotej rybce",
            "Trzy małe świnki",
        ],
    },

    {
        title: "Geografia",
        content: ["jezioro", "morze", "dolina", "góry", "rzeka", "pustynia", "ocean", "las", "dżungla", "wyspa", "lodowiec", "wodospad", "wulkan", "jaskinia", "biegun", "bagno"],
    },

    {
        title: "Instrumenty muzyczne",
        content: [
            "gitara elektryczna",
            "pianino",
            "skrzypce",
            "bębny",
            "gitara basowa",
            "saksofon",
            "wiolonczela",
            "flet",
            "klarnet",
            "trąbka",
            "trójkąt",
            "ukulele",
            "harfa",
            "dudy",
            "harmonijka",
            "banjo",
        ],
    },

    {
        title: "Malarze",
        content: [
            "Jan Matejko",
            "Salvador Dali",
            "Pablo Picasso",
            "Vincent van Gogh",
            "Claude Monet",
            "Andy Warhol",
            "Leonardo da Vinci",
            "Michał Anioł",
            "Banksy",
            "Zdzisław Beksiński",
            " Gustav Klimt",
            "Caravaggio",
            "Rembrandt",
            "Hans Memling",
            "Frida Khalo",
            "Witkacy",
        ],
    },

    {
        title: "Gry",
        content: [
            "Monopoly",
            "scrabble",
            "5 sekund",
            "Zgadnij kto",
            "Ryzyko",
            "Operacja",
            "Twister",
            "kalambury",
            "statki",
            "Węże i drabiny",
            "Cluedo",
            "szachy",
            "warcaby",
            "chińczyk",
            "Jenga",
            "grzybobranie",
        ],
    },

    {
        title: "Ludy i cywilizacje",
        content: [
            "Rzymianie",
            "Egipcjanie",
            "Majowie",
            "Aborygeni",
            "Aztekowie",
            "Japończycy",
            "Persowie",
            "Grecy",
            "Turcy",
            "wikingowie",
            "Inkowie",
            "Słowianie",
            "Indianie",
            "Chińczycy",
            "Spartanie",
            "obcy",
        ],
    },

    {
        title: "Zawody",
        content: [
            "rybak",
            "drwal",
            "pielęgniarka",
            "kelner",
            "latarnik",
            "nurek",
            "księgowy",
            "nauczyciel",
            "kierowca",
            "ochroniarz",
            "kucharz",
            "architekt",
            "policjant",
            "prawnik",
            "dekarz",
            "rzeźnik",
        ],
    },

    {
        title: "Gwiazdy sportu",
        content: [
            "Tiger Woods",
            "Lionel Messi",
            "Michael Jordan",
            "David Beckham",
            "Michael Phelps",
            "Serene Williams",
            "Muhammad Ali",
            "Adam Małysz",
            "Michael Schumacher",
            "Robert Lewandowski",
            "Agnieszka Radwańska",
            "Marit Bjoergen",
            "Lewis Hamilton",
            "Roger Federer",
            "Usain Bolt",
            "Mike Tyson",
        ],
    },

    {
        title: "Kultura i sztuka",
        content: [
            "malarstwo",
            "rzeźba",
            "architektura",
            "taniec",
            "literatura",
            "opera",
            "kabaret",
            "komiks",
            "grafika",
            "muzyka",
            "teatr",
            "film",
            "rzemiosło artystyczne",
            "graffiti",
            "moda",
            "fotografia",
        ],
    },

    {
        title: "Napoje",
        content: [
            "kawa",
            "herbata",
            "lemoniada",
            "cola",
            "wino",
            "piwo",
            "szampan",
            "tequila",
            "gorąca czekolada",
            "shake",
            "kompot",
            "woda",
            "oranżada",
            "sok pomarańczowy",
            "mleko",
            "maślanka",
        ],
    },

    {
        title: "Pisarze",
        content: [
            "William Shakespeare",
            "J.R.R. Tolkien",
            "Paulo Coelho",
            "J.K. Rowling",
            "Stephen King",
            "Ernest Hemingway",
            "Henryk Sienkiewicz",
            "Karol Dickens",
            "Aleksander Dumas",
            "Lew Tołstoj",
            "Jane Austen",
            "Mark Twain",
            "Danielle Steel",
            "Harlan Coben",
            "Dan Brown",
            "Agatha Christie",
        ],
    },

    {
        title: "Zoo",
        content: ["słoń", "żyrafa", "koala", "tygrys", "lew", "gepard", "surykatka", "antylopa", "struś", "wielbłąd", "orzeł", "papuga", "hipopotam", "aligator", "zebra", "goryl"],
    },

    {
        title: "Miasta",
        content: [
            "Nowy Jork",
            "Moskwa",
            "Warszawa",
            "Londyn",
            "Paryż",
            "Rzym",
            "Rio de Janeiro",
            "Sydney",
            "Tokio",
            "Ateny",
            "Kair",
            "Pekin",
            "Sopot",
            "Jerozolima",
            "Stambuł",
            "Buenos Aires",
        ],
    },

    {
        title: "Hobby",
        content: [
            "filatelistyka",
            "gry planszowe",
            "modelarstwo",
            "robienie na drutach",
            "wędkarstwo",
            "czytanie",
            "malowanie",
            "ogrodnictwo",
            "żeglarstwo",
            "podróże",
            "bieganie",
            "garncarstwo",
            "gotowanie",
            "joga",
            "fotografia",
            "wspinaczka",
        ],
    },

    {
        title: "Desery",
        content: [
            "lody",
            "budyń",
            "czekolada",
            "kisiel",
            "beza",
            "pączek",
            "sernik",
            "jabłecznik",
            "piernik",
            "tort",
            "ptyś",
            "bita śmietana",
            "owoce",
            "batonik",
            "drożdżówka",
            "bombonierka",
        ],
    },

    {
        title: "Seriale telewizyjne",
        content: [
            "Przyjaciele",
            "Seks w wielkim mieście",
            "Star Trek",
            "The Walking Dead",
            "Breaking Bad",
            "Klan",
            "Latający cyrk Monty Pythona",
            "Moda na sukces",
            "M jak miłość",
            "Z archiwum X",
            "House of Cards",
            "Dr House",
            "Miasteczko Twin Peaks",
            "Simpsonowie",
            "Gra o tron",
            "Czterej pancerni i pies",
        ],
    },

    {
        title: "Fobie",
        content: ["duchy", "pająki", "potwory", "szczury", "toalety", "węże", "zarazki", "klowny", "igły", "psy", "ptaki", "robaki", "dzieci", "ciemność", "winda", "samoloty"],
    },

    {
        title: "Wynalazki",
        content: [
            "zapałki",
            "proch",
            "koło",
            "druk",
            "komputer",
            "internet",
            "kompas",
            "samolot",
            "telewizor",
            "elektryczność",
            "pismo",
            "silnik parowy",
            "samochód",
            "telefon",
            "aparat fotograficzny",
            "radio",
        ],
    },

    {
        title: "Przedmioty w szkole",
        content: [
            "matematyka",
            "chemia",
            "fizyka",
            "biologia",
            "historia",
            "przyroda",
            "geografia",
            "język angielski",
            "wiedza o społeczeństwie",
            "język polski",
            "plastyka",
            "muzyka",
            "wychowanie fizyczne",
            "łacina",
            "religia",
            "technika",
        ],
    },

    {
        title: "środki transportu",
        content: [
            "samolot",
            "samochód",
            "czołg",
            "helikopter",
            "statek wycieczkowy",
            "poduszkowiec",
            "motocykl",
            "autobus",
            "hulajnoga",
            "kolejka linowa",
            "rower",
            "balon",
            "pociąg",
            "statek kosmiczny",
            "latający dywan",
            "trolejbus",
        ],
    },

    {
        title: "Książki dla dzieci",
        content: [
            "Hobbit, czyli tam i z powrotem",
            "Piotruś Pan",
            "W pustyni i w puszczy",
            "101 dalmatyńczyków",
            "Dzieci z Bullerbyn",
            "Harry Potter i Kamień Filozoficzny",
            "Alicja w Krainie Czarów",
            "Opowieści z Narnii",
            "Przygody Tomka Sawyera",
            "Detektyw Pozytywka",
            "Charlie i fabryka czekolady",
            " Ania z Zielonego Wzgórza",
            "Kubuś Puchatek",
            "Mikołajek",
            "Księga Dżungli",
            "Doktor Dolittle i jego zwierzęta",
        ],
    },

    {
        title: "Jedzenie",
        content: ["pizza", "ziemniak", "ryba", "pierogi", "makaron", "sałatka", "zupa", "chleb", "jajko", "ser", "jabłko", "kurczak", "parówka", "frytki", "bigos", "szynka"],
    },

    {
        title: "Kraje",
        content: [
            "Wielka Brytania",
            "Hiszpania",
            "Japonia",
            "Brazylia",
            "Francja",
            "Stany Zjednoczone",
            "Włochy",
            "Australia",
            "Polska",
            "Meksyk",
            "Indie",
            "Izrael",
            "Kanada",
            "Chiny",
            "Rosja",
            "Egipt",
        ],
    },

    {
        title: "Bajkowe zwierzaki",
        content: [
            "Garfield",
            "Scooby-Doo",
            "Miś Yogi",
            "Królik Bugs",
            "Myszka Miki",
            "Goofy",
            "Reksio",
            "Miś Uszatek",
            "Nemo",
            "Kłapouchy",
            "Snoopy",
            "Bambi",
            "Dumbo",
            "Świnka Peppa",
            "Simba",
            "Pszczółka Maja",
        ],
    },

    {
        title: "Pomieszczenia",
        content: [
            "kuchnia",
            "korytarz",
            "szklarnia",
            "sypialnia",
            "łazienka",
            "jadalnia",
            "biuro",
            "salon",
            "strych",
            "piwnica",
            "loch",
            "wychodek",
            "spiżarnia",
            "bunkier",
            "szopa",
            "garaż",
        ],
    },

    {
        title: "Święta",
        content: [
            "Boże Narodzenie",
            "Dzień Ojca",
            "Narodowe Święta Niepodległości",
            "Wielkanoc",
            "Dzień Dziecka",
            "prima aprilis",
            "tłusty czwartek",
            "walentynki",
            "Wszystkich Świętych",
            "Dzień Kobiet",
            "Święto Trzech Króli",
            "Dzień Matki",
            "sylwester",
            "andrzejki",
            "majówka",
            "Halloween",
        ],
    },

    {
        title: "Postacie fikcyjne",
        content: [
            "Indiana Jones",
            "Shrek",
            "Spider-Man",
            "Kobieta-Kot",
            "James Bond",
            "Bridget Jones",
            "księżniczka Leia",
            "Calineczka",
            "Dracula",
            "Lara Croft",
            "Robin Hood",
            "Harry Potter",
            "Super Mario",
            "Homer Simpson",
            "Herkules",
            "Batman",
        ],
    },

    {
        title: "Kosmetyki",
        content: [
            "mydło",
            "żel pod prysznic",
            "lakier do paznokci",
            "maseczka do twarzy",
            "szampon",
            "krem",
            "szminka",
            "tusz do rzęs",
            "pasta do zębów",
            "odżywka do włosów",
            "puder",
            "cień do powiek",
            "dezodorant",
            "żel do włosów",
            "samoopalacz",
            "pianka do golenia",
        ],
    },

    {
        title: "Zespoły muzyczne",
        content: [
            "The Beatles",
            "The Rolling Stones",
            "AC/DC",
            "Nirvana",
            "Pink Floyd",
            "Aerosmith",
            "Guns N Roses",
            "Queen",
            "The Beach Boys",
            "Red Hot Chili Peppers",
            "Kiss",
            "The Jackson 5",
            "ABBA",
            "Budka Suflera",
            "Lady Pank",
            "U2",
        ],
    },

    {
        title: "Science fiction i fantasy",
        content: [
            "Gwiezdne wojny",
            "Władca Pierścieni",
            "Star Trek",
            "Blade Runner",
            "Obcy",
            "2001: Odyseja kosmiczna",
            "Terminator",
            "Igrzyska śmierci",
            "Diuna",
            "Wiedźmin",
            "Alicja w Krainie Czarów",
            "Podróże Guliwera",
            "Wojna światów",
            "Marsjanin",
            "WALL-E",
            "Edward Nożycoręki",
        ],
    },
];
